<?php

namespace app\models;

use Faker\Provider\DateTime;
use webvimark\modules\UserManagement\components\UserConfig;
use yii\db\ActiveRecord;
use yii\web\User;

/**
 * @property  integer $autore
 * @property \DateTime $creato_il
 * @property  integer $modificato_da
 * @property \DateTime $modificato_il
 *
 *
 * @property User $creatore
 * @property User $modificante
 */
class UrbiModel extends ActiveRecord
{

    public function save($runValidation = true, $attributeNames = null)
    {
        $now = new \DateTime();
        if ($this->isNewRecord) {
            $this->autore = \Yii::$app->user->id;
            $this->creato_il = $now->format('Y-m-d H:i:s');
        }
        $this->modificato_da = \Yii::$app->user->id;
        $this->modificato_il =  $now->format('Y-m-d H:i:s');
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }


    /**
     * Gets query for [[UserConfig]].
     *
     * @return UserConfig
     */
    public function getCreatore()
    {
        return new UserConfig($this->autore);
    }
    /**
     * Gets query for [[UserConfig]].
     *
     * @return UserConfig
     */
    public function getModificante()
    {
            return new UserConfig($this->modificato_da);
    }

}